import { Injectable, Logger } from '@nestjs/common';
import { BaseWorker, ZeebeJob, BpmnError } from '../base.worker';
import { PrismaService } from '../../../common/prisma/prisma.service';

interface GenerateWCFInput {
    serviceOrderId: string;
    providerId: string;
    customerId: string;
    checkoutId?: string;
}

interface GenerateWCFOutput {
    wcfId: string;
    wcfNumber: string;
    generatedAt: string;
}

@Injectable()
export class GenerateWCFWorker extends BaseWorker<GenerateWCFInput, GenerateWCFOutput> {
    protected readonly logger = new Logger(GenerateWCFWorker.name);
    readonly taskType = 'generate-wcf';

    constructor(private readonly prisma: PrismaService) {
        super();
    }

    async handle(job: ZeebeJob<GenerateWCFInput>): Promise<GenerateWCFOutput> {
        const { serviceOrderId, providerId, customerId } = job.variables;

        if (!serviceOrderId || !providerId || !customerId) {
            throw new BpmnError('INVALID_INPUT', 'Missing required fields');
        }

        this.logger.log(`Generating WCF for service order ${serviceOrderId}`);

        const serviceOrder = await this.prisma.serviceOrder.findUnique({
            where: { id: serviceOrderId },
        });

        if (!serviceOrder) {
            throw new BpmnError('SERVICE_ORDER_NOT_FOUND', `Service order ${serviceOrderId} not found`);
        }

        // Generate WCF number
        const wcfNumber = `WCF-${Date.now().toString().slice(-8)}`;

        // Create WCF record
        // Using mock data for required JSON fields as we don't have full context here
        const wcf = await this.prisma.workCompletionForm.create({
            data: {
                wcfNumber,
                serviceOrderId,
                countryCode: serviceOrder.countryCode,
                businessUnit: serviceOrder.businessUnit,
                status: 'DRAFT',
                serviceDate: new Date(),
                // Mock data for required fields
                customerInfo: serviceOrder.customerInfo || {},
                technicianInfo: {},
                providerInfo: {},
                serviceLocation: serviceOrder.serviceAddress || {},
                workSummary: 'Generated by Camunda Workflow',
                workDetails: {},
                totalLaborHours: 0,
            },
        });

        return {
            wcfId: wcf.id,
            wcfNumber: wcf.wcfNumber,
            generatedAt: wcf.createdAt.toISOString(),
        };
    }
}
